version: '3'
services:
  web:
    build: .
    depends_on:
      - mongoConsort
    command: bash -c "npm i && cd src && npm run dev"
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    working_dir: /usr/app
    ports:
      - '3000:3000'
  mongo:
    container_name: mongoConsort
    image: mongo
    ports:
      - '27017:27017'
  nginx:
    build: ./nginx-docker
    ports:
      - '80:80'
