version: '3'
services:
  web_devmoi:
    build: .
    depends_on:
      - mongoDevmoi
    command: bash -c "yarn && yarn dev"
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    working_dir: /usr/app
    ports:
      - '3001:3000'
      - '9545:9545'
  mongoDevmoi:
    container_name: mongoDevmoi
    image: mongo
    ports:
      - '27018:27017'
  # truffle_devmoi:
  #   build: ./docker-truffle
  #   ports:
  #     - '9545:8545'