version: '3'
services:
  ganache:
    image: moikapy/moiganache
    command: 'ganache-cli -h 0.0.0.0 -s devmoi --acctKeys ./wallets.json -e 9001 -q -n'
    restart: always
    volumes:
      - .:/usr/app
    environment:
      MMS: $MMS
    ports:
      - '8545:8545'
  web:
    build: .
    restart: always
    depends_on:
      - ganache
      - mongo
    command: bash -c "yarn --silent && yarn dev"
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    working_dir: /usr/app
    ports:
      - '3001:3000'
  mongo:
    container_name: mongo
    depends_on:
      - ganache
    restart: always
    image: mongo
    ports:
      - '27018:27017'
