version: '3'
services:
  web_devmoi:
    build: .
    depends_on:
      - mongo_devmoi
    command: bash -c "npm i && cd src && npm run dev"
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    working_dir: /usr/app
    ports:
      - '3001:3000'
  mongo_devmoi:
    image: mongo
    ports:
      - '27018:27017'